export const dnsUtil: Array<dnsInterface> = [
  {
    dns: 'Ember',
    karmaDnsMod: 50,
    kockatartalekDnsMod: 3,
    atlagMagFerfi: 180,
    atlagMagNo: 166,
    atlagMag: 173,
    atlagSulyFerfi: 86,
    atlagSulyNo: 70,
    atlagSuly: 78,
    VarhatoEletkorFerfi: 65,
    VarhatoEletkorNo: 75,
    VarhatoEletkorMax: 110,
    kepessegek: [
      '+1 Kockatartalék'
    ],
    szorzoRuhazat: 1,
    szorzoEletvitel: 1,
  },
  {
    dns: 'Tünde',
    karmaDnsMod: 25,
    fizUgyDnsMod: 1,
    asztEroDnsMod: 2,
    asztGyoDnsMod: 1,
    atlagMagFerfi: 186,
    atlagMagNo: 174,
    atlagMag: 174,
    atlagSulyFerfi: 80,
    atlagSulyNo: 66,
    atlagSuly: 73,
    VarhatoEletkorFerfi: 75,
    VarhatoEletkorNo: 85,
    VarhatoEletkorMax: 150,
    kepessegek: [
      'Éjszakai látás'
    ],
    szorzoRuhazat: 1,
    szorzoEletvitel: 1,
  },
  {
    dns: 'Törpe',
    karmaDnsMod: 10,
    fizEroDnsMod: 2,
    fizKitDnsMod: 1,
    fizGyoDnsMod: -1,
    asztKitDnsMod: 1,
    atlagMagFerfi: 137,
    atlagMagNo: 123,
    atlagMag: 130,
    atlagSulyFerfi: 60,
    atlagSulyNo: 48,
    atlagSuly: 54,
    VarhatoEletkorFerfi: 70,
    VarhatoEletkorNo: 80,
    VarhatoEletkorMax: 130,
    kepessegek: [
      '+2 Állóképesség Mérgezés ellen',
      'Hőlátás'
    ],
    szorzoRuhazat: 1,
    szorzoEletvitel: 1,
  },
  {
    dns: 'Ork',
    karmaDnsMod: 20,
    fizEroDnsMod: 2,
    fizKitDnsMod: 2,
    asztEroDnsMod: -1,
    atlagMagFerfi: 200,
    atlagMagNo: 180,
    atlagMag: 190,
    atlagSulyFerfi: 135,
    atlagSulyNo: 110,
    atlagSuly: 123,
    VarhatoEletkorFerfi: 55,
    VarhatoEletkorNo: 65,
    VarhatoEletkorMax: 90,
    kepessegek: [
      '+1 Fizikai Sérülés ellen',
      'Éjszakai látás'
    ],
    szorzoRuhazat: 1,
    szorzoEletvitel: 1,
  },
  {
    dns: 'Troll',
    karmaDnsMod: 0,
    fizEroDnsMod: 3,
    fizKitDnsMod: 3,
    fizUgyDnsMod: -1,
    asztEroDnsMod: -1,
    pancelDnsMod: 1,
    atlagMagFerfi: 260,
    atlagMagNo: 240,
    atlagMag: 250,
    atlagSulyFerfi: 300,
    atlagSulyNo: 240,
    atlagSuly: 270,
    VarhatoEletkorFerfi: 55,
    VarhatoEletkorNo: 65,
    VarhatoEletkorMax: 100,
    kepessegek: [
      '+2 Fizikai Sérülés ellen',
      'Hőlátás',
      '+1 Páncél'
    ],
    szorzoRuhazat: 1.5,
    szorzoEletvitel: 1.5,
  }
];

export interface dnsInterface {
  dns: string,
  karmaDnsMod: number,
  atlagMagFerfi: number,
  atlagMagNo: number,
  atlagMag: number,
  atlagSulyFerfi: number,
  atlagSulyNo: number,
  atlagSuly: number,
  VarhatoEletkorFerfi: number,
  VarhatoEletkorNo: number,
  VarhatoEletkorMax: number,

  fizEroDnsMod?: number,
  fizUgyDnsMod?: number,
  fizGyoDnsMod?: number,
  fizKitDnsMod?: number,
  pancelDnsMod?: number,

  asztEroDnsMod?: number,
  asztGyoDnsMod?: number,
  asztKitDnsMod?: number,

  kockatartalekDnsMod?: number,
  kepessegek: Array<string>,

  szorzoRuhazat: number,
  szorzoEletvitel: number,
}
