export const npcUtil: Array<any> = [

  // Kápmegyeri Elit Troll Különítmény
  {
    nev: 'Frieza',
    dns: 'troll',
    nem: 'férfi',
    anyanyelv: 'Magyar',
    kor: 39,
    magassag: 235,
    suly: 210,
    testalkat: 'izmos',
    szemszin: 'lila',
    borszin: 'fehér',
    hajszin: 'fekete',
    hajstilus: 'kopasz',
    kaszt: 'fizikai adeptus',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Kápmegyeri Elit Troll Különítmény',
    leiras: 'Kevély, mindenkivel harcolni akar, nagyszájú és lenéz mindenkit, akit egy kicsit is gyengébbnek vél. Ettől függetlenül nem rosszindulatú, csak a modora nem a legkifinomultabb. Az igazi keresztneve Elemér, amit a csapattársai rendszeresen felemlegetnek, amitől dühös lesz és mindenkit megfenyeget, aki viccet mer csinálni belőle. Becenevéhez igazítva öltözködik :)'
  },
  {
    nev: 'Starscream',
    dns: 'troll',
    nem: 'férfi',
    anyanyelv: 'Magyar',
    kor: 25,
    magassag: 290,
    suly: 220,
    testalkat: 'átlagos',
    szemszin: 'piros',
    borszin: 'barna',
    hajszin: 'fekete',
    hajstilus: 'félhosszú',
    kaszt: 'drónrigó',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Kápmegyeri Elit Troll Különítmény',
    leiras: 'Jókedvű, harsány fickó, kicsit szeret áskálódni, de amúgy minden rendben van vele. nem mellesleg Transformers fan, egy egész seregnyi Decepticon-drón áll a rendelkezésére.'
  },
  {
    nev: 'Skeletor',
    dns: 'troll',
    nem: 'férfi',
    anyanyelv: 'Magyar',
    kor: 52,
    magassag: 310,
    suly: 260,
    testalkat: 'izmos',
    szemszin: 'fekete',
    borszin: 'sárgás',
    hajszin: 'szőke',
    hajstilus: 'vállig érő',
    kaszt: 'utcai szamuráj',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Kápmegyeri Elit Troll Különítmény',
    leiras: 'Brutális méretű, de amúgy csendes exkatona, tele krómmal. Azt beszélik, puszta kézzel meg tud állítani egy tankot és az RPG lepattan róla. Ha a csapatáról van szó, akár a saját életét is hajlandó feláldozni.'
  },
  {
    nev: 'Rita the witch',
    dns: 'troll',
    nem: 'nő',
    anyanyelv: 'Magyar',
    kor: 33,
    magassag: 265,
    suly: 195,
    testalkat: 'átlagos',
    szemszin: 'kék',
    borszin: 'szürke',
    hajszin: 'fehér',
    hajstilus: 'hosszú, hátközépig érő, egyenes',
    kaszt: 'Föld elementalista',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Kápmegyeri Elit Troll Különítmény',
    leiras: 'hermetikus mágus, aki a föld elementálok mellett kötelezte el magát. Ha védelemről van szó, ő az első vonalban foglal helyet. Harsány, de amúgy kedves személyisége teljesen ellentéte a robosztus földnek, melynek elkötelezte magát.'
  },
  {
    nev: 'Queen Beryl',
    dns: 'troll',
    nem: 'nő',
    anyanyelv: 'Magyar',
    kor: 28,
    magassag: 270,
    suly: 190,
    testalkat: 'átlagos',
    szemszin: 'narancsságra',
    borszin: 'fehér',
    hajszin: 'vörös',
    hajstilus: 'hosszú, egyenes, hátközépig érő',
    kaszt: 'Farkas sámán',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Kápmegyeri Elit Troll Különítmény',
    leiras: ''
  },
  {
    nev: 'Farkas -Csodálatos Pókarc- János',
    dns: 'pókszellem',
    nem: 'férfi',
    anyanyelv: 'Magyar',
    kor: 35,
    magassag: 175,
    suly: 85,
    testalkat: 'átlagos',
    szemszin: 'fekete',
    borszin: 'szürke',
    hajszin: 'fekete',
    hajstilus: 'rövid, tüsi',
    kaszt: 'kísérleti alany',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Szabadúszó',
    leiras: 'Eredetileg autókereskedőként dolgozott, amíg a póksámánok el nem fogták és el nem kezdték az átalakítását. A procedúrába azonban hiba csúszott, a királynő halálával a megkötés nélküli szellemek távoztak, így János lelke megmenekült, de addigra a teste már félig pókká változott. Folyamatosan ját a szája és mindenkinek el akar adni valamit. Legnagyobb félelme, hogy feleség és gyerek nélkül hal meg, ezen pedig a jelenlegi állapota sem segít.',
    idezetek: [
      "Terranak: Hú, há, szereted a bort? Igen? Van egy tök jó eladó szőlőstelek Balatonbogláron, na, érdekel?",
      "Daneyanak: Hölgyem, kérem legyen a feleségem! Egy cigány jósnő papagája megjósolta, hogy amikor a halál árnyéka fenyeget, megtalálom az igazit... és én most úgy érzem, a mai napot nem élem túl",
      "Hú, de jó, mindenkinek szupermenő álneve van, nekem is kell egy! Mondjuk póksrác, vagy pókügynük, vagy neeem... póknepper! Vagy vagy vaaagy, Csodálatos Pókarc!"
    ]
  },
  {
    nev: 'Adolf von Kartoffelsuppe főhadnagy',
    dns: 'ember',
    nem: 'férfi',
    anyanyelv: 'Német',
    kor: 45,
    magassag: 170,
    suly: 80,
    testalkat: 'izmos',
    szemszin: 'kék',
    borszin: 'rózsaszín',
    hajszin: 'szőke',
    hajstilus: 'rövid, hullámos',
    kaszt: 'mesterkém',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Elit Horror Szakasz',
    leiras: 'Ausztriából gyerekkorában áttelepült katona, karrierjét szobafestőként kezdte, de nem talált kihívást a munkában, ezért bevonult és a Honvédségnél az osztagvezetésig vitte. Több harcot megélt, számos krómmal megpakolt, büszke ember. Szigorú, precíz, de nem okoz neki gondot, hogy ha szükséges, lazábbra vegye.',
    idezetek: [
      "Guten tag, mein freund! A nevem Adolf... nein, nein, nein, nicht Hitler du dummkopf. Adolf von Kartoffelsuppe, főhadnagy! Aki viccet csinálni meine name, azt lefokozom... vagy pofozom."
    ]
  },
  {
    nev: 'Krueger Mátyás',
    dns: 'ember',
    nem: 'férfi',
    anyanyelv: 'Magyar',
    kor: 42,
    magassag: 181,
    suly: 95,
    testalkat: 'izmos',
    szemszin: 'zöld',
    borszin: 'rózsaszín',
    hajszin: 'fekete',
    hajstilus: 'vállig érő, hullámos',
    kaszt: 'zsoldos',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Elit Horror Szakasz',
    leiras: '',
    idezetek: []
  },
  {
    nev: 'Lecter Ádám',
    dns: 'ember',
    nem: 'férfi',
    anyanyelv: 'Magyar',
    kor: 51,
    magassag: 175,
    suly: 95,
    testalkat: 'izmos',
    szemszin: 'barna',
    borszin: 'rózsaszín',
    hajszin: 'barna',
    hajstilus: 'rövid, tüsi',
    kaszt: 'dekás',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Elit Horror Szakasz',
    leiras: '',
    idezetek: []
  },
  {
    nev: 'Szomorú Annabelle',
    dns: 'ember',
    nem: 'nő',
    anyanyelv: 'Magyar',
    kor: 25,
    magassag: 170,
    suly: 65,
    testalkat: 'karcsú, izmos',
    szemszin: 'kék',
    borszin: 'rózsaszín',
    hajszin: 'szőke',
    hajstilus: 'hosszú, hátközépig érő, hullámos',
    kaszt: 'mesterlövész',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Elit Horror Szakasz',
    leiras: '',
    idezetek: [],
  },
  {
    nev: 'Kredenc',
    dns: 'törpe',
    nem: 'férfi',
    anyanyelv: 'Magyar',
    kor: 55,
    magassag: 135,
    suly: 50,
    testalkat: 'átlagos',
    szemszin: 'zöld',
    borszin: 'rózsaszín',
    hajszin: 'vörös',
    hajstilus: 'mohikán, hosszú fonott szakáll',
    kaszt: 'járműrigó',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Hófehérke és a hét törpe',
    leiras: 'Alapvetően jó kedvű figura, amit a rengeteg szikrafű fogyasztással még magasabbra szintre emel. Betépve is jobban vezet, mint mások józanul: állítólag az ország egyik legjobb pilótája, számos járművet képes vezetni. Mindene a családja, ezért a veszélyes Honvédségi munkát szívből gyűlöli és ha lehet, passzolja.',
    idezetek: [
      "Jaaaj, csávókáim, hát mi van veletek? Gyertek pattanjatok be a tragacsomba!",
      "Fúúú, ez atom cucc! Kérsz egy slukkot a rakétámból?",
      "Jaj spanok, annyira komálom a búrátokat, ha ennek vége, lazuljunk már együtt"
    ],
  },
  {
    nev: 'Horváth Norbert admirális',
    dns: 'ember',
    nem: 'férfi',
    anyanyelv: 'Magyar',
    kor: 62,
    magassag: 182,
    suly: 105,
    testalkat: 'izmos, de kicsit pocakos',
    szemszin: 'barna',
    borszin: 'rózsaszín',
    hajszin: 'fehér',
    hajstilus: 'ujjnyi hosszú, jól fésült, mellközépig érő szakállal',
    kaszt: 'zsoldos',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Magyar Honvédség',
    leiras: 'A tábornok alapvetően kedves, kicsit flúgos, de munkában szigorú és precíz ember, amolyan apafigura a jó értelemben. Bár idősebb, a világ változásait könnyebben követte, nyitottsága sokak bizalmát elnyerte. Tiszteletet árasztó személyiségét nehéz nem kedvelni, tipikusan jó vezető mind emberi, mind taktikai értelemben.',
    idezetek: [
      "Csodás napra ébredtünk uraim. Országunk jövője az Önök kezében és én minden eszközzel támogatni fogom Önöket, hogy sikerrel járjanak!",
      "Sajnálom, hogy így gondolja ezredes. Ha lemondana a haragjáról, képes lenne teljes valójában látni a világot és megélni az örömöket, amiktől oly szorgalamasan menekül",
      "Ezredes, előterjesztettem magát. Én most biztosan meghalok. Kérem, vigyázzon a kis elit csapatunkra... tegyen meg mindent, hogy sikerrel védhessenek meg minket az eljövendő fenyegetésektől!"
    ]
  },
  {
    nev: 'Kovács Albert ezredes',
    dns: 'ember',
    nem: 'férfi',
    anyanyelv: 'Magyar',
    kor: 56,
    magassag: 183,
    suly: 95,
    testalkat: 'izmos',
    szemszin: 'kék',
    borszin: 'rózsaszín',
    hajszin: 'őszes fekete',
    hajstilus:  'rövid, tüsi, oldalt felnyírva',
    kaszt: 'utcai szamuráj',
    alapTulSzint: 0,
    szakTulSzint: 0,
    alapSzakertSzint: 0,
    szakteruletSzint: 0,
    frakcio: 'Magyar Honvédség',
    leiras: 'Keménykötésű, full króm, metahumángyűlölő és varázslatellenes fickó (a családját egy metahumán varázsló intézte el), aminek rendszeresen hangot is ad. A feje folyamatosan lenéző fintorban van, mindenkit megvet, akit egy kicsit is gyengébbnek gondol. Mivel a munkája és a parancsok megkövetelik, ezért kelletlenül együttműködik bárkivel, de közben jól láthatóan vergődik. Az egyetlen jó pontja, hogy bár lekezelő a stílusa, a szóbeli sértegetésnél tovább nem megy, közvetlenül ártani nem fog senkinek.',
    idezetek: [
      "Már megint nekem kell foglalkoznom ezzel a metahumán csürhével. Remélem nem rondítotok oda sehova, még a végén nekem kell utánatok takarítani",
      "Ne gondolják, hogy amiért elitnek nevezik magukat, többet érnek bárki másnál. Még egy csótányt jobban becsülök maguknál",
      "Nézzétek, mondtam dolgokat amiket most... mélységesen bánok. Sajnálom. Tényleg. Igyekszem helyrehozni, bármeddig is tartson!"
    ]
  }
];






// {
//   nev: '',
//   dns: '',
//   nem: '',
//   kor: 0,
//   magassag: 0,
//   suly: 0,
//   testalkat: '',
//   szemszin: '',
//   borszin: '',
//   hajszin: '',
//   hajstilus: '',
//   kaszt: '',
//   alapTulSzint: 0,
//   szakTulSzint: 0,
//   alapSzakertSzint: 0,
//   szakteruletSzint: 0,
//   leiras: ''
//   idezetek: [],
// },
// Tudor - Tróger: nyomozó, arrogáns Sherlock jellegű
// Vidor - Kredenc: járműrigó, always high, go with the flow, bro
// Morgó - Smucig: dekás bankár, mindenért morog, főleg azért, hogy mennyibe fog neki ez kerülni
// Szundi - Zwerg: fizikai adeptus, már ha fent tud maradni, specialitása a rendkívül gyors mozgás és állva is el tud aludni (kertitörpe)
// Szende - Rezsó: nehézfegyveres, nagggyon meleg, neki vannak a legszerteágazóbb infói
// Hapci - Slukk: varázsló, folyamatosan tubákot szív és prüszköl
// Kuka - Sparhelt: lángszórós zsoldos, piromániás, mindig tudja hol a sárkány, de nem mondja, mert titkos
