export const skillsUtil: Array<SkillInterface> = [
  {id: 'atletika', multi: false, nev: 'Atlétika', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul:'fizUgy'},
  {id: 'rejtozes', multi: false, nev: 'Rejtőzés', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul:'fizUgy'},
  {id: 'kozelharc', multi: false, nev: 'Közelharc', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul:'fizUgy'},
  {id: 'tuzfegyverek', multi: false, nev: 'Tűzfegyverek', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul:'fizUgy'},
  {id: 'vadonjaras', multi: false, nev: 'Vadonjárás', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'asztGyo'},
  {id: 'erzekeles', multi: false, nev: 'Érzékelés', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'asztGyo'},
  {id: 'jarmuvezetes', multi: false, nev: 'Járművezetés', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'reakcio'},
  {id: 'idezes', multi: false, nev: 'Idézés', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'magia'},
  {id: 'asztralvilag', multi: false, nev: 'Asztrálvilág', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'asztGyo'},
  {id: 'varazslas', multi: false, nev: 'Varázslás', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'magia'},
  {id: 'kibervilag', multi: false, nev: 'Kibervilág', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'asztUgy'},
  {id: 'varazsmuvesseg', multi: false, nev: 'Varázsművesség', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'magia'},
  {id: 'szineszet', multi: false, nev: 'Színészet', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'asztEro'},
  {id: 'befolyasolas', multi: false, nev: 'Befolyásolás', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'asztEro'},
  {id: 'biotech', multi: false, nev: 'Biotech', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'asztUgy'},
  {id: 'elektronika', multi: false, nev: 'Elektronika', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'asztUgy'},
  {id: 'muszaki', multi: false, nev: 'Műszaki tudás', nevKieg: '', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'asztUgy'},
  {id: 'egzotikusfegyverek', multi: true, nev: '', nevKieg: 'Egzotikus fegyv.', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 3, kapTul: 'fizUgy'},
  {id: 'szakmaESz', multi: true, nev: '', nevKieg: 'Szakma', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'fizUgy'},
  {id: 'fizUgyESz', multi: true, nev: '', nevKieg: 'Egyedi, Ügyesség', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'fizUgy'},
  {id: 'asztUgyESz', multi: true, nev: '', nevKieg: 'Egyedi, Logika', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'asztUgy'},
  {id: 'asztGyoESz', multi: true, nev: '', nevKieg: 'Egyedi, Intuíció', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'asztGyo'},
  {id: 'magiaESz', multi: true, nev: '', nevKieg: 'Egyedi, Mágia', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'magia'},
  {id: 'reakcioESz', multi: true, nev: '', nevKieg: 'Egyedi, Reakció', csoport: 'Aktív Szakértelmek', faName: 'activeSkills', karmaKtsg: 5, kapTul: 'reakcio'},
  // ismeret
  {id: 'erdeklodes', multi: true, nev: '', nevKieg: 'Érdeklődési körök', csoport: 'Ismeret Szakértelmek', faName: 'knowledgeSkills', karmaKtsg: 3, kapTul: 'asztUgy'},
  {id: 'hatodikvilag', multi: true, nev: '', nevKieg: '6. világbeli ism.', csoport: 'Ismeret Szakértelmek', faName: 'knowledgeSkills', karmaKtsg: 3, kapTul: 'asztUgy'},
  {id: 'hatter', multi: true, nev: '', nevKieg: 'Háttér ismeretek', csoport: 'Ismeret Szakértelmek', faName: 'knowledgeSkills', karmaKtsg: 3, kapTul: 'asztUgy'},
  {id: 'iskola', multi: true, nev: '', nevKieg: 'Iskolai ismeretek', csoport: 'Ismeret Szakértelmek', faName: 'knowledgeSkills', karmaKtsg: 3, kapTul: 'asztUgy'},
  {id: 'utcai', multi: true, nev: '', nevKieg: 'Utcai ismeretek', csoport: 'Ismeret Szakértelmek', faName: 'knowledgeSkills', karmaKtsg: 3, kapTul: 'asztUgy'},
  // nyelvi
  {id: 'nyelv', multi: true, nev: '', nevKieg: 'Nyelv', csoport: 'Nyelvi Szakértelmek', faName: 'languageSkills', karmaKtsg: 3, kapTul: 'asztUgy'},
  {id: 'iras', multi: true, nev: '', nevKieg: 'Írás/olvasás', csoport: 'Nyelvi Szakértelmek', faName: 'languageSkills', karmaKtsg: 3, kapTul: 'asztUgy'},
];

export const skillsSpecUtil: Array<SkillSpecInterface> = [
  {id: 'futas', multi: false, nev: 'Futás', specOf: 'atletika', karmaKtsg: 2},
  {id: 'uszas', multi: false, nev: 'Úszás', specOf: 'atletika', karmaKtsg: 2},
  {id: 'ugras', multi: false, nev: 'Ugrás', specOf: 'atletika', karmaKtsg: 2},
  {id: 'akrobatika', multi: false, nev: 'Akrobatika', specOf: 'atletika', karmaKtsg: 2},
  {id: 'maszas', multi: false, nev: 'Mászás', specOf: 'atletika', karmaKtsg: 2},
  {id: 'buvarkodas', multi: false, nev: 'Búvárkodás', specOf: 'atletika', karmaKtsg: 2},
  {id: 'dobofegyverek', multi: false, nev: 'Dobófegyverek', specOf: 'atletika', karmaKtsg: 2},
  {id: 'lofegyverek', multi: false, nev: 'Lőfegyverek', specOf: 'atletika', karmaKtsg: 2},

  {id: 'lopozas', multi: false, nev: 'Lopózás', specOf: 'rejtozes', karmaKtsg: 2},
  {id: 'rejtozes', multi: false, nev: 'Rejtőzködés', specOf: 'rejtozes', karmaKtsg: 2},
  {id: 'zsebmetszes', multi: false, nev: 'Zsebmetész', specOf: 'rejtozes', karmaKtsg: 2},
  {id: 'elrejtes', multi: false, nev: 'Elrejtés', specOf: 'rejtozes', karmaKtsg: 2},
  {id: 'szabadulas', multi: false, nev: 'Szabadulás', specOf: 'rejtozes', karmaKtsg: 2},
  {id: 'zarfeltores', multi: false, nev: 'Zárfeltörés', specOf: 'rejtozes', karmaKtsg: 2},

  {id: 'fegyveretelenharc', multi: false, nev: 'Fegyvertelen harc', specOf: 'kozelharc', karmaKtsg: 2},
  {id: 'elesfegyverek', multi: false, nev: 'Éles fegyverek', specOf: 'kozelharc', karmaKtsg: 2},
  {id: 'tompafegyverek', multi: false, nev: 'Tompa fegyverek', specOf: 'kozelharc', karmaKtsg: 2},
  {id: 'szalfegyverek', multi: false, nev: 'Szálfegyverek', specOf: 'kozelharc', karmaKtsg: 2},
  {id: 'vizalattiharc', multi: false, nev: 'Víz alatti harc', specOf: 'kozelharc', karmaKtsg: 2},
  {id: 'kabitofegyverek', multi: false, nev: 'Kábítófegyverek', specOf: 'kozelharc', karmaKtsg: 2},
  {id: 'kiberfegyverek', multi: false, nev: 'Kiberfegyverek', specOf: 'kozelharc', karmaKtsg: 2},

  {id: 'pisztolyok', multi: false, nev: 'Pisztolyok', specOf: 'tuzfegyverek', karmaKtsg: 2},
  {id: 'soretespuskak', multi: false, nev: 'Sörétes puskák', specOf: 'tuzfegyverek', karmaKtsg: 2},
  {id: 'geppisztolyok', multi: false, nev: 'Géppisztolyok', specOf: 'tuzfegyverek', karmaKtsg: 2},
  {id: 'puskak', multi: false, nev: 'Puskák', specOf: 'tuzfegyverek', karmaKtsg: 2},
  {id: 'rohampuskak', multi: false, nev: 'Rohampuskák', specOf: 'tuzfegyverek', karmaKtsg: 2},
  {id: 'agyuk', multi: false, nev: 'Ágyúk', specOf: 'tuzfegyverek', karmaKtsg: 2},
  {id: 'lezerfegyverek', multi: false, nev: 'Lézerfegyverek', specOf: 'tuzfegyverek', karmaKtsg: 2},
  {id: 'raketavetok', multi: false, nev: 'Rakétavetők', specOf: 'tuzfegyverek', karmaKtsg: 2},

  {id: 'tajekozodas', multi: false, nev: 'Tájékozódás', specOf: 'vadonjaras', karmaKtsg: 2},
  {id: 'tulelels', multi: false, nev: 'Túlélőtechnikák', specOf: 'vadonjaras', karmaKtsg: 2},
  {id: 'nyomolvasas', multi: false, nev: 'Nyomolvasás', specOf: 'vadonjaras', karmaKtsg: 2},
  {id: 'idomitas', multi: false, nev: 'Idomítás', specOf: 'vadonjaras', karmaKtsg: 2},

  {id: 'vizualis', multi: false, nev: 'Vizuális érz.', specOf: 'erzekeles', karmaKtsg: 2},
  {id: 'aura', multi: false, nev: 'Auraérzékelés', specOf: 'erzekeles', karmaKtsg: 2},
  {id: 'tapintas', multi: false, nev: 'Tapintás', specOf: 'erzekeles', karmaKtsg: 2},
  {id: 'szaglas', multi: false, nev: 'Szaglás', specOf: 'erzekeles', karmaKtsg: 2},
  {id: 'hallas', multi: false, nev: 'Hallás', specOf: 'erzekeles', karmaKtsg: 2},

  {id: 'szarazfoldijarmu', multi: false, nev: 'Szárazföldi jármű', specOf: 'jarmuvezetes', karmaKtsg: 2},
  {id: 'vizijarmu', multi: false, nev: 'Vizi jármű', specOf: 'jarmuvezetes', karmaKtsg: 2},
  {id: 'legijarmu', multi: false, nev: 'Légi jármű', specOf: 'jarmuvezetes', karmaKtsg: 2},
  {id: 'specialisjarmi', multi: false, nev: 'Speciális', specOf: 'jarmuvezetes', karmaKtsg: 2},

  {id: 'szellemhivas', multi: false, nev: 'Szellem hívás', specOf: 'idezes', karmaKtsg: 2},
  {id: 'szellemiranyitas', multi: false, nev: 'Szellem irányítás', specOf: 'idezes', karmaKtsg: 2},
  {id: 'szellemuzes', multi: false, nev: 'Szellem elűzés', specOf: 'idezes', karmaKtsg: 2},

  {id: 'asztralisharc', multi: false, nev: 'Asztrális harc', specOf: 'asztralvilag', karmaKtsg: 2},
  {id: 'asztralislenyomatok', multi: false, nev: 'Asztrális lenyomatok', specOf: 'asztralvilag', karmaKtsg: 2},
  {id: 'asztralolvasas', multi: false, nev: 'Asztrálolvasás', specOf: 'asztralvilag', karmaKtsg: 2},

  {id: 'varazsmondas', multi: false, nev: 'Varázsmondás', specOf: 'varazslas', karmaKtsg: 2},
  {id: 'varazsvedelem', multi: false, nev: 'Varázsvédelem', specOf: 'varazslas', karmaKtsg: 2},
  {id: 'varazsmegtores', multi: false, nev: 'Varázsmegtörés', specOf: 'varazslas', karmaKtsg: 2},
  {id: 'ritualisvarazslas', multi: false, nev: 'Rituális varázslás', specOf: 'varazslas', karmaKtsg: 2},

  {id: 'kiberharc', multi: false, nev: 'Kiberharc', specOf: 'kibervilag', karmaKtsg: 2},
  {id: 'rendszervedelem', multi: false, nev: 'Rendszervédelem', specOf: 'kibervilag', karmaKtsg: 2},
  {id: 'rendszeriranyitas', multi: false, nev: 'Rendszerirányítás', specOf: 'kibervilag', karmaKtsg: 2},
  {id: 'rendszerfeltores', multi: false, nev: 'Rendszerfeltörés', specOf: 'kibervilag', karmaKtsg: 2},

  {id: 'alkimia', multi: false, nev: 'Alkímia', specOf: 'varazsmuvesseg', karmaKtsg: 2},
  {id: 'ereklyekeszites', multi: false, nev: 'Ereklyekészítés', specOf: 'varazsmuvesseg', karmaKtsg: 2},
  {id: 'ereklyemegtores', multi: false, nev: 'Ereklye megtörés', specOf: 'varazsmuvesseg', karmaKtsg: 2},

  {id: 'megszemelyesites', multi: false, nev: 'Megszemélyesítés', specOf: 'szineszet', karmaKtsg: 2},
  {id: 'eloadas', multi: false, nev: 'Előadás', specOf: 'szineszet', karmaKtsg: 2},
  {id: 'alcazas', multi: false, nev: 'Álcázás', specOf: 'szineszet', karmaKtsg: 2},
  {id: 'szinjatszas', multi: false, nev: 'Színjátszás', specOf: 'szineszet', karmaKtsg: 2},

  {id: 'etikett', multi: false, nev: 'Etikett', specOf: 'befolyasolas', karmaKtsg: 2},
  {id: 'tanitas', multi: false, nev: 'Tanítás', specOf: 'befolyasolas', karmaKtsg: 2},
  {id: 'megfelelmites', multi: false, nev: 'Megfélelmítés', specOf: 'befolyasolas', karmaKtsg: 2},
  {id: 'csapatvezetes', multi: false, nev: 'Csapatvezetés', specOf: 'befolyasolas', karmaKtsg: 2},
  {id: 'targyalas', multi: false, nev: 'Tárgyalás', specOf: 'befolyasolas', karmaKtsg: 2},

  {id: 'biotech', multi: false, nev: 'Biotechnológia', specOf: 'biotech', karmaKtsg: 2},
  {id: 'kibertech', multi: false, nev: 'Kibertechnológia', specOf: 'biotech', karmaKtsg: 2},
  {id: 'elsosegely', multi: false, nev: 'Elsősegély', specOf: 'biotech', karmaKtsg: 2},
  {id: 'gyogyszerek', multi: false, nev: 'Gyógyszerészet', specOf: 'biotech', karmaKtsg: 2},
  {id: 'kemia', multi: false, nev: 'Kémia', specOf: 'biotech', karmaKtsg: 2},

  {id: 'szamitogep', multi: false, nev: 'Számítógép', specOf: 'elektronika', karmaKtsg: 2},
  {id: 'szoftver', multi: false, nev: 'Szoftver', specOf: 'elektronika', karmaKtsg: 2},
  {id: 'hardver', multi: false, nev: 'Hardver', specOf: 'elektronika', karmaKtsg: 2},
  {id: 'programozas', multi: false, nev: 'Programozás', specOf: 'elektronika', karmaKtsg: 2},

  {id: 'robbantas', multi: false, nev: 'Robbantás', specOf: 'muszaki', karmaKtsg: 2},
  {id: 'iparimechanika', multi: false, nev: 'Ipari mechanika', specOf: 'muszaki', karmaKtsg: 2},
  {id: 'jarmumechanika', multi: false, nev: 'Jármű mechanika', specOf: 'muszaki', karmaKtsg: 2},
  {id: 'repulestechnika', multi: false, nev: 'Repüléstechnika', specOf: 'muszaki', karmaKtsg: 2},
  {id: 'hidromechanika', multi: false, nev: 'Hidromechanika', specOf: 'muszaki', karmaKtsg: 2},
  {id: 'fegyverkovacs', multi: false, nev: 'Fegyverkovács', specOf: 'muszaki', karmaKtsg: 2},
  {id: 'pancelkovacs', multi: false, nev: 'Páncélkovács', specOf: 'muszaki', karmaKtsg: 2},

  {id: 'egyeniSpec', multi: false, nev: '', specOf: '', karmaKtsg: 2},
];

export interface SkillInterface {
  id: string,
  multi: boolean,
  nev: string,
  nevKieg: string,
  csoport: string,
  faName: string,
  karmaKtsg: number,
  kapTul: string,
}

export interface SkillSpecInterface {
  id: string,
  multi: boolean,
  nev: string,
  specOf: string,
  karmaKtsg: number,
}
